set(__QT_DEPLOY_TARGET_pytem-inversion-gui_FILE C:/Users/pamcl/OneDrive - Danmarks Tekniske Universitet/Dokumenter/Projects/Python/pyTEM/gui/pyTEM-native-cpp-v0.3.0/cpp_gui/build-ninja/pytem-inversion-gui.exe)
set(__QT_DEPLOY_TARGET_pytem-inversion-gui_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_pytem-inversion-gui_RUNTIME_DLLS C:/msys64/ucrt64/bin/Qt6Widgets.dll;C:/msys64/ucrt64/bin/Qt6Gui.dll;C:/msys64/ucrt64/bin/Qt6Core.dll)
set(__QT_DEPLOY_TARGET_pytem-native-tests_FILE C:/Users/pamcl/OneDrive - Danmarks Tekniske Universitet/Dokumenter/Projects/Python/pyTEM/gui/pyTEM-native-cpp-v0.3.0/cpp_gui/build-ninja/pytem-native-tests.exe)
set(__QT_DEPLOY_TARGET_pytem-native-tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_pytem-native-tests_RUNTIME_DLLS )
